/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Principal.Clases.Usuario;
import Principal.Clases.ListaUsuarios;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class FrmEstadisticas extends javax.swing.JFrame {

    /**
     * Creates new form FrmEstadisticas
     */
    public FrmEstadisticas() {
        initComponents();
        Usuario user = ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario];
        lbNombre.setText(user.getNombre());
        lbApellido.setText(user.getApellido());
        lbEdad.setText(String.valueOf(user.getEdad()));
        lbSexo.setText(user.getSexo());
        lbGrado.setText(user.getGrado());
        lbOpTotales.setText(String.valueOf(user.getOpTotales()));
        lbOpCorrectas.setText(String.valueOf(user.getOpCorrectas()));
        lbOpIncorrectas.setText(String.valueOf(user.getOpIncorrectas()));
        lbBits.setText(String.valueOf(user.getBits()));
        lbPorcentAcierto.setText(String.valueOf(user.getPorcentAcierto()));

        lbIniciales.setText(ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].iniciales);
        pintarResuelto();

        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void pintarResuelto() {
        ArrayList<JLabel> Niveles = new ArrayList<>();
        Niveles.add(resuelto1);
        Niveles.add(resuelto2);
        Niveles.add(resuelto3);
        Niveles.add(resuelto4);
        Niveles.add(resuelto5);
        Niveles.add(resuelto6);
        Niveles.add(resuelto7);
        lbNivel.setText("NIVEL " + ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getNivel());
        int n = ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getOpCorrectas();
        while (n > 7) {
            n -= 7;
        }

        resuelto1.setForeground(Color.black);
        resuelto2.setForeground(Color.black);
        resuelto3.setForeground(Color.black);
        resuelto4.setForeground(Color.black);
        resuelto5.setForeground(Color.black);
        resuelto6.setForeground(Color.black);
        resuelto7.setForeground(Color.black);

        for (int i = 0; i < n; i++) {
            Niveles.get(i).setForeground(Color.red);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBorrar = new javax.swing.JButton();
        lbIniciales = new javax.swing.JLabel();
        resuelto3 = new javax.swing.JLabel();
        lbNivel = new javax.swing.JLabel();
        resuelto6 = new javax.swing.JLabel();
        resuelto1 = new javax.swing.JLabel();
        resuelto5 = new javax.swing.JLabel();
        resuelto2 = new javax.swing.JLabel();
        resuelto4 = new javax.swing.JLabel();
        resuelto7 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        lbEdad = new javax.swing.JLabel();
        lbSexo = new javax.swing.JLabel();
        lbGrado = new javax.swing.JLabel();
        lbOpTotales = new javax.swing.JLabel();
        lbOpCorrectas = new javax.swing.JLabel();
        lbOpIncorrectas = new javax.swing.JLabel();
        lbBits = new javax.swing.JLabel();
        lbPorcentAcierto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBorrar.setBackground(new java.awt.Color(255, 153, 153));
        btnBorrar.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrar.setText("<html>BORRAR PERFIL<html>");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 170, 40));

        lbIniciales.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lbIniciales.setForeground(new java.awt.Color(0, 0, 0));
        lbIniciales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIniciales.setText("KM");
        jPanel1.add(lbIniciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 26, -1, -1));

        resuelto3.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto3.setForeground(new java.awt.Color(0, 0, 0));
        resuelto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto3.setText("•");
        jPanel1.add(resuelto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 30, 30));

        lbNivel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lbNivel.setForeground(new java.awt.Color(0, 0, 0));
        lbNivel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNivel.setText("NIVEL 1");
        jPanel1.add(lbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 130, -1));

        resuelto6.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto6.setForeground(new java.awt.Color(0, 0, 0));
        resuelto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto6.setText("•");
        jPanel1.add(resuelto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 30, 30));

        resuelto1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto1.setForeground(new java.awt.Color(0, 0, 0));
        resuelto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto1.setText("•");
        jPanel1.add(resuelto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 30, 30));

        resuelto5.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto5.setForeground(new java.awt.Color(0, 0, 0));
        resuelto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto5.setText("•");
        jPanel1.add(resuelto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 30, 30));

        resuelto2.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto2.setForeground(new java.awt.Color(0, 0, 0));
        resuelto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto2.setText("•");
        jPanel1.add(resuelto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 30, 30));

        resuelto4.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto4.setForeground(new java.awt.Color(0, 0, 0));
        resuelto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto4.setText("•");
        jPanel1.add(resuelto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 30, 30));

        resuelto7.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto7.setForeground(new java.awt.Color(0, 0, 0));
        resuelto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto7.setText("•");
        jPanel1.add(resuelto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 30, 30));

        lbNombre.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(0, 0, 0));
        lbNombre.setText("Nombre");
        jPanel1.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 130, 30));

        lbApellido.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbApellido.setForeground(new java.awt.Color(0, 0, 0));
        lbApellido.setText("Apellido");
        jPanel1.add(lbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 130, 30));

        lbEdad.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbEdad.setForeground(new java.awt.Color(0, 0, 0));
        lbEdad.setText("Edad");
        jPanel1.add(lbEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 140, 30));

        lbSexo.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbSexo.setForeground(new java.awt.Color(0, 0, 0));
        lbSexo.setText("Sexo");
        jPanel1.add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 140, 30));

        lbGrado.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbGrado.setForeground(new java.awt.Color(0, 0, 0));
        lbGrado.setText("Grado");
        jPanel1.add(lbGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 70, 30));

        lbOpTotales.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbOpTotales.setForeground(new java.awt.Color(0, 0, 0));
        lbOpTotales.setText("Op Totales");
        jPanel1.add(lbOpTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 120, 20));

        lbOpCorrectas.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbOpCorrectas.setForeground(new java.awt.Color(0, 0, 0));
        lbOpCorrectas.setText("Op");
        jPanel1.add(lbOpCorrectas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 110, 20));

        lbOpIncorrectas.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbOpIncorrectas.setForeground(new java.awt.Color(0, 0, 0));
        lbOpIncorrectas.setText("Op");
        jPanel1.add(lbOpIncorrectas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 80, 30));

        lbBits.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbBits.setForeground(new java.awt.Color(0, 0, 0));
        lbBits.setText("Bits");
        jPanel1.add(lbBits, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 140, 30));

        lbPorcentAcierto.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbPorcentAcierto.setForeground(new java.awt.Color(0, 0, 0));
        lbPorcentAcierto.setText("% de Acierto");
        jPanel1.add(lbPorcentAcierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 140, 20));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Frm Estadisticas.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        new FrmMain().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int borrar = JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas borrar este perfil?. \nEsta acción es irreversible!", "ADVERTENCIA", 0, JOptionPane.WARNING_MESSAGE);
        //Yes = 0
        //No = 1
        if (borrar == 0) {
            ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario] = new Usuario();
            ControladorDatos.Datos.guardarPerfiles();
            new FrmPerfiles().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEstadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbBits;
    private javax.swing.JLabel lbEdad;
    private javax.swing.JLabel lbGrado;
    private javax.swing.JLabel lbIniciales;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbOpCorrectas;
    private javax.swing.JLabel lbOpIncorrectas;
    private javax.swing.JLabel lbOpTotales;
    private javax.swing.JLabel lbPorcentAcierto;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel resuelto1;
    private javax.swing.JLabel resuelto2;
    private javax.swing.JLabel resuelto3;
    private javax.swing.JLabel resuelto4;
    private javax.swing.JLabel resuelto5;
    private javax.swing.JLabel resuelto6;
    private javax.swing.JLabel resuelto7;
    // End of variables declaration//GEN-END:variables
}
