package Principal;

import Extras.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Victor
 */
public final class FrmExtras extends javax.swing.JFrame {

    /**
     * Creates new form ventana1
     */
    public FrmExtras() {
        initComponents();
        transparencia();
        lbIniciales.setText(ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].iniciales);
        pintarResuelto();
        this.setLocationRelativeTo(null);
    }

    private void pintarResuelto() {
        ArrayList<JLabel> Niveles = new ArrayList<>();
        Niveles.add(resuelto1);
        Niveles.add(resuelto2);
        Niveles.add(resuelto3);
        Niveles.add(resuelto4);
        Niveles.add(resuelto5);
        Niveles.add(resuelto6);
        Niveles.add(resuelto7);
        lbNivel.setText("NIVEL " + ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getNivel());
        int n = ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getOpCorrectas();
        while (n > 7) {
            n -= 7;
        }

        resuelto1.setForeground(Color.black);
        resuelto2.setForeground(Color.black);
        resuelto3.setForeground(Color.black);
        resuelto4.setForeground(Color.black);
        resuelto5.setForeground(Color.black);
        resuelto6.setForeground(Color.black);
        resuelto7.setForeground(Color.black);

        for (int i = 0; i < n; i++) {
            Niveles.get(i).setForeground(Color.red);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resuelto7 = new javax.swing.JLabel();
        resuelto6 = new javax.swing.JLabel();
        resuelto5 = new javax.swing.JLabel();
        resuelto4 = new javax.swing.JLabel();
        resuelto3 = new javax.swing.JLabel();
        resuelto2 = new javax.swing.JLabel();
        resuelto1 = new javax.swing.JLabel();
        lbNivel = new javax.swing.JLabel();
        lbIniciales = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resuelto7.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto7.setForeground(new java.awt.Color(0, 0, 0));
        resuelto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto7.setText("•");
        jPanel1.add(resuelto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 30, 30));

        resuelto6.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto6.setForeground(new java.awt.Color(0, 0, 0));
        resuelto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto6.setText("•");
        jPanel1.add(resuelto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 30, 30));

        resuelto5.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto5.setForeground(new java.awt.Color(0, 0, 0));
        resuelto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto5.setText("•");
        jPanel1.add(resuelto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 30, 30));

        resuelto4.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto4.setForeground(new java.awt.Color(0, 0, 0));
        resuelto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto4.setText("•");
        jPanel1.add(resuelto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 30, 30));

        resuelto3.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto3.setForeground(new java.awt.Color(0, 0, 0));
        resuelto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto3.setText("•");
        jPanel1.add(resuelto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 30, 30));

        resuelto2.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto2.setForeground(new java.awt.Color(0, 0, 0));
        resuelto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto2.setText("•");
        jPanel1.add(resuelto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 30, 30));

        resuelto1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto1.setForeground(new java.awt.Color(0, 0, 0));
        resuelto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto1.setText("•");
        jPanel1.add(resuelto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 30, 30));

        lbNivel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lbNivel.setForeground(new java.awt.Color(0, 0, 0));
        lbNivel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNivel.setText("NIVEL 1");
        jPanel1.add(lbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 110, -1));

        lbIniciales.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lbIniciales.setForeground(new java.awt.Color(0, 0, 0));
        lbIniciales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIniciales.setText("KM");
        jPanel1.add(lbIniciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 20, 30, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Num&Op2.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        jPanel1.add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 230, 150));

        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 220, 150));

        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 220, 150));

        btn4.setText("jButton1");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 220, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void transparencia() {
        boton1.setOpaque(false);
        boton1.setContentAreaFilled(false);
        boton1.setBorderPainted(false);
        boton2.setOpaque(false);
        boton2.setContentAreaFilled(false);
        boton2.setBorderPainted(false);
        boton3.setOpaque(false);
        boton3.setContentAreaFilled(false);

    }
    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        FrmOpCombinadas b = new FrmOpCombinadas();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        FrmMayorMenorIgual a = new FrmMayorMenorIgual();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        FrmNumLitToCifras c = new FrmNumLitToCifras();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton3ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new FrmMain().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        new FrmEcuaciones().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmExtras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbIniciales;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel resuelto1;
    private javax.swing.JLabel resuelto2;
    private javax.swing.JLabel resuelto3;
    private javax.swing.JLabel resuelto4;
    private javax.swing.JLabel resuelto5;
    private javax.swing.JLabel resuelto6;
    private javax.swing.JLabel resuelto7;
    // End of variables declaration//GEN-END:variables

}
