package Principal;

import java.awt.Color;
import Geometria.Clases.*;
import Geometria.Formularios.*;
import Principal.*;
import java.util.ArrayList;
import javax.swing.JLabel;

public class FrmGeometria extends javax.swing.JFrame {

    public FrmGeometria() {
        initComponents();
        setLocationRelativeTo(null);
        transparencia();
        lbIniciales.setText(ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].iniciales);
        pintarResuelto();
    }

    private void pintarResuelto() {
        ArrayList<JLabel> Niveles = new ArrayList<>();
        Niveles.add(resuelto1);
        Niveles.add(resuelto2);
        Niveles.add(resuelto3);
        Niveles.add(resuelto4);
        Niveles.add(resuelto5);
        Niveles.add(resuelto6);
        Niveles.add(resuelto7);
        lbNivel.setText("NIVEL " + ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getNivel());
        int n = ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getOpCorrectas();
        while (n > 7) {
            n -= 7;
        }

        resuelto1.setForeground(Color.black);
        resuelto2.setForeground(Color.black);
        resuelto3.setForeground(Color.black);
        resuelto4.setForeground(Color.black);
        resuelto5.setForeground(Color.black);
        resuelto6.setForeground(Color.black);
        resuelto7.setForeground(Color.black);

        for (int i = 0; i < n; i++) {
            Niveles.get(i).setForeground(Color.red);
        }
    }

    private void transparencia() {
        btn_circulo.setOpaque(false);
        btn_circulo.setContentAreaFilled(false);
        btn_circulo.setBorderPainted(false);

        btn_rectangulo.setOpaque(false);
        btn_rectangulo.setContentAreaFilled(false);
        btn_rectangulo.setBorderPainted(false);

        btn_cuadrado.setOpaque(false);
        btn_cuadrado.setContentAreaFilled(false);
        btn_cuadrado.setBorderPainted(false);

        btn_triangulo.setOpaque(false);
        btn_triangulo.setContentAreaFilled(false);
        btn_triangulo.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_editable = new javax.swing.ButtonGroup();
        PanelBackground = new javax.swing.JPanel();
        resuelto7 = new javax.swing.JLabel();
        resuelto6 = new javax.swing.JLabel();
        resuelto5 = new javax.swing.JLabel();
        resuelto4 = new javax.swing.JLabel();
        resuelto3 = new javax.swing.JLabel();
        resuelto2 = new javax.swing.JLabel();
        resuelto1 = new javax.swing.JLabel();
        lbNivel = new javax.swing.JLabel();
        lbIniciales = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        btn_triangulo = new javax.swing.JButton();
        btn_circulo = new javax.swing.JButton();
        btn_rectangulo = new javax.swing.JButton();
        btn_cuadrado = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBackground.setBackground(new java.awt.Color(153, 153, 255));
        PanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resuelto7.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto7.setForeground(new java.awt.Color(0, 0, 0));
        resuelto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto7.setText("•");
        PanelBackground.add(resuelto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 30, 30));

        resuelto6.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto6.setForeground(new java.awt.Color(0, 0, 0));
        resuelto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto6.setText("•");
        PanelBackground.add(resuelto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 30, 30));

        resuelto5.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto5.setForeground(new java.awt.Color(0, 0, 0));
        resuelto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto5.setText("•");
        PanelBackground.add(resuelto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 30, 30));

        resuelto4.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto4.setForeground(new java.awt.Color(0, 0, 0));
        resuelto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto4.setText("•");
        PanelBackground.add(resuelto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 30, 30));

        resuelto3.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto3.setForeground(new java.awt.Color(0, 0, 0));
        resuelto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto3.setText("•");
        PanelBackground.add(resuelto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 30, 30));

        resuelto2.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto2.setForeground(new java.awt.Color(0, 0, 0));
        resuelto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto2.setText("•");
        PanelBackground.add(resuelto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 30, 30));

        resuelto1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto1.setForeground(new java.awt.Color(0, 0, 0));
        resuelto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto1.setText("•");
        PanelBackground.add(resuelto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 30, 30));

        lbNivel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lbNivel.setForeground(new java.awt.Color(0, 0, 0));
        lbNivel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNivel.setText("NIVEL 1");
        PanelBackground.add(lbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, -1));

        lbIniciales.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lbIniciales.setForeground(new java.awt.Color(0, 0, 0));
        lbIniciales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIniciales.setText("KM");
        PanelBackground.add(lbIniciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 18, 30, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FrmGeometria (1).png"))); // NOI18N
        PanelBackground.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_triangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/triangulo.png"))); // NOI18N
        btn_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trianguloActionPerformed(evt);
            }
        });
        PanelBackground.add(btn_triangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 180, -1));

        btn_circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circulo.png"))); // NOI18N
        btn_circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_circuloActionPerformed(evt);
            }
        });
        PanelBackground.add(btn_circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        btn_rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rectangulo.png"))); // NOI18N
        btn_rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rectanguloActionPerformed(evt);
            }
        });
        PanelBackground.add(btn_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 160, -1));

        btn_cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadrado.png"))); // NOI18N
        btn_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuadradoActionPerformed(evt);
            }
        });
        PanelBackground.add(btn_cuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 140, 130));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        PanelBackground.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trianguloActionPerformed
        this.setVisible(false);
        new FrmTriangulo().setVisible(true);
    }//GEN-LAST:event_btn_trianguloActionPerformed

    private void btn_circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_circuloActionPerformed
        this.setVisible(false);
        new FrmCirculo().setVisible(true);
    }//GEN-LAST:event_btn_circuloActionPerformed

    private void btn_rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rectanguloActionPerformed
        this.setVisible(false);
        new FrmRectangulo().setVisible(true);
    }//GEN-LAST:event_btn_rectanguloActionPerformed

    private void btn_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuadradoActionPerformed
        this.setVisible(false);
        new FrmCuadrado().setVisible(true);
    }//GEN-LAST:event_btn_cuadradoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new FrmMain().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGeometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGeometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGeometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGeometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGeometria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel PanelBackground;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btn_circulo;
    private javax.swing.JButton btn_cuadrado;
    private javax.swing.JButton btn_rectangulo;
    private javax.swing.JButton btn_triangulo;
    private javax.swing.ButtonGroup group_editable;
    private javax.swing.JLabel lbIniciales;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel resuelto1;
    private javax.swing.JLabel resuelto2;
    private javax.swing.JLabel resuelto3;
    private javax.swing.JLabel resuelto4;
    private javax.swing.JLabel resuelto5;
    private javax.swing.JLabel resuelto6;
    private javax.swing.JLabel resuelto7;
    // End of variables declaration//GEN-END:variables
}
