package Principal;

import java.awt.Color;
import Geometria.Clases.*;
import Geometria.Formularios.*;
import Principal.*;

public class FrmGeometria extends javax.swing.JFrame {

    public FrmGeometria() {
        initComponents();
        setLocationRelativeTo(null);
        transparencia();
    }

    private void transparencia() {
        btn_circulo.setOpaque(false);
        btn_circulo.setContentAreaFilled(false);
        btn_circulo.setBorderPainted(false);

        btn_rectangulo.setOpaque(false);
        btn_rectangulo.setContentAreaFilled(false);
        btn_rectangulo.setBorderPainted(false);

        btn_cuadrado.setOpaque(false);
        btn_cuadrado.setContentAreaFilled(false);
        btn_cuadrado.setBorderPainted(false);

        btn_triangulo.setOpaque(false);
        btn_triangulo.setContentAreaFilled(false);
        btn_triangulo.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_editable = new javax.swing.ButtonGroup();
        PanelBackground = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        btn_triangulo = new javax.swing.JButton();
        btn_circulo = new javax.swing.JButton();
        btn_rectangulo = new javax.swing.JButton();
        btn_cuadrado = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBackground.setBackground(new java.awt.Color(153, 153, 255));
        PanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(153, 0, 0));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("FIGURAS");
        PanelBackground.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 70));

        btn_triangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/triangulo.png"))); // NOI18N
        btn_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trianguloActionPerformed(evt);
            }
        });
        PanelBackground.add(btn_triangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btn_circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circulo.png"))); // NOI18N
        btn_circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_circuloActionPerformed(evt);
            }
        });
        PanelBackground.add(btn_circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        btn_rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rectangulo.png"))); // NOI18N
        btn_rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rectanguloActionPerformed(evt);
            }
        });
        PanelBackground.add(btn_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        btn_cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadrado.png"))); // NOI18N
        btn_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuadradoActionPerformed(evt);
            }
        });
        PanelBackground.add(btn_cuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        PanelBackground.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trianguloActionPerformed
        this.setVisible(false);
        new FrmTriangulo().setVisible(true);
    }//GEN-LAST:event_btn_trianguloActionPerformed

    private void btn_circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_circuloActionPerformed
        this.setVisible(false);
        new FrmCirculo().setVisible(true);
    }//GEN-LAST:event_btn_circuloActionPerformed

    private void btn_rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rectanguloActionPerformed
        this.setVisible(false);
        new FrmRectangulo().setVisible(true);
    }//GEN-LAST:event_btn_rectanguloActionPerformed

    private void btn_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuadradoActionPerformed
        this.setVisible(false);
        new FrmCuadrado().setVisible(true);
    }//GEN-LAST:event_btn_cuadradoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new FrmMain().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGeometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGeometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGeometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGeometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGeometria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBackground;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btn_circulo;
    private javax.swing.JButton btn_cuadrado;
    private javax.swing.JButton btn_rectangulo;
    private javax.swing.JButton btn_triangulo;
    private javax.swing.ButtonGroup group_editable;
    private javax.swing.JLabel lbl_title;
    // End of variables declaration//GEN-END:variables
}
