/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Principal.Clases.ListaUsuarios;
import NumerosYOperaciones.FrmNumLitToCifras;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Gabriel
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setLocationRelativeTo(null);
        lbIniciales.setText(ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].iniciales);

        pintarResuelto();
    }

    private void pintarResuelto() {
        ArrayList<JLabel> Niveles = new ArrayList<>();
        Niveles.add(resuelto1);
        Niveles.add(resuelto2);
        Niveles.add(resuelto3);
        Niveles.add(resuelto4);
        Niveles.add(resuelto5);
        Niveles.add(resuelto6);
        Niveles.add(resuelto7);
        lbNivel.setText("NIVEL " + ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getNivel());
        int n = ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getOpCorrectas();
        while (n > 7) {
            n -= 7;
        }

        resuelto1.setForeground(Color.black);
        resuelto2.setForeground(Color.black);
        resuelto3.setForeground(Color.black);
        resuelto4.setForeground(Color.black);
        resuelto5.setForeground(Color.black);
        resuelto6.setForeground(Color.black);
        resuelto7.setForeground(Color.black);

        for (int i = 0; i < n; i++) {
            Niveles.get(i).setForeground(Color.red);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resuelto7 = new javax.swing.JLabel();
        resuelto6 = new javax.swing.JLabel();
        resuelto5 = new javax.swing.JLabel();
        resuelto4 = new javax.swing.JLabel();
        resuelto3 = new javax.swing.JLabel();
        resuelto2 = new javax.swing.JLabel();
        resuelto1 = new javax.swing.JLabel();
        lbNivel = new javax.swing.JLabel();
        lbIniciales = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnOP = new javax.swing.JButton();
        btnExtras = new javax.swing.JButton();
        btnGeometria = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(119, 171, 189));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resuelto7.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto7.setForeground(new java.awt.Color(0, 0, 0));
        resuelto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto7.setText("•");
        jPanel1.add(resuelto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 30, 30));

        resuelto6.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto6.setForeground(new java.awt.Color(0, 0, 0));
        resuelto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto6.setText("•");
        jPanel1.add(resuelto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 30, 30));

        resuelto5.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto5.setForeground(new java.awt.Color(0, 0, 0));
        resuelto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto5.setText("•");
        jPanel1.add(resuelto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 30, 30));

        resuelto4.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto4.setForeground(new java.awt.Color(0, 0, 0));
        resuelto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto4.setText("•");
        jPanel1.add(resuelto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 30, 30));

        resuelto3.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto3.setForeground(new java.awt.Color(0, 0, 0));
        resuelto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto3.setText("•");
        jPanel1.add(resuelto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 30, 30));

        resuelto2.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto2.setForeground(new java.awt.Color(0, 0, 0));
        resuelto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto2.setText("•");
        jPanel1.add(resuelto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 30, 30));

        resuelto1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        resuelto1.setForeground(new java.awt.Color(0, 0, 0));
        resuelto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resuelto1.setText("•");
        jPanel1.add(resuelto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 30, 30));

        lbNivel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lbNivel.setForeground(new java.awt.Color(0, 0, 0));
        lbNivel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNivel.setText("NIVEL 1");
        jPanel1.add(lbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 110, -1));

        lbIniciales.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lbIniciales.setForeground(new java.awt.Color(0, 0, 0));
        lbIniciales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIniciales.setText("KM");
        jPanel1.add(lbIniciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 142, 30, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MainprincipalEducaGebra2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 580, 510));

        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setBorder(null);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 50));

        btnOP.setToolTipText("Operaciones Basicas");
        btnOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOPActionPerformed(evt);
            }
        });
        jPanel1.add(btnOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 240, 70));

        btnExtras.setToolTipText("Mayor y Menor");
        btnExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 230, 80));

        btnGeometria.setToolTipText("Geometría");
        btnGeometria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeometriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGeometria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 322, 230, 80));

        btnInfo.setToolTipText("Cerrar");
        btnInfo.setBorder(null);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        jPanel1.add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        new FrmPerfiles().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOPActionPerformed
        new FrmCuatroOp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOPActionPerformed

    private void btnExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtrasActionPerformed
        new FrmNumerosYOperaciones().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExtrasActionPerformed

    private void btnGeometriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeometriaActionPerformed
        new FrmGeometria().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGeometriaActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        new FrmEstadisticas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExtras;
    private javax.swing.JButton btnGeometria;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnOP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbIniciales;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel resuelto1;
    private javax.swing.JLabel resuelto2;
    private javax.swing.JLabel resuelto3;
    private javax.swing.JLabel resuelto4;
    private javax.swing.JLabel resuelto5;
    private javax.swing.JLabel resuelto6;
    private javax.swing.JLabel resuelto7;
    // End of variables declaration//GEN-END:variables
}
