package Extras;

import Principal.FrmExtras;
import Principal.ListaUsuarios;
import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Victor
 */
public class FrmMayorMenorIgual extends javax.swing.JFrame {

    int n11, n21, n31, n41, n51, n61;
    boolean okCalcular = false;
    String resultado = "";

    /**
     * Creates new form ventana2
     */
    private void nuevaOp() {
        Random com = new Random();
        int caso = (int) (Math.random() * (6 - 1 + 1) + 1);
        switch (caso) {
            case 1:
                n11 = com.nextInt(999);
                n21 = n11;
                n1.setText(String.valueOf(n11));
                n2.setText(String.valueOf(n21));
                break;
            default:
                n11 = com.nextInt(999);
                n21 = com.nextInt(999);
                n1.setText(String.valueOf(n11));
                n2.setText(String.valueOf(n21));
        }
    }

    public FrmMayorMenorIgual() {
        initComponents();
        this.setLocationRelativeTo(null);
        nuevaOp();
        actualizarBits();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        n1 = new javax.swing.JLabel();
        resultado1 = new javax.swing.JTextField();
        n2 = new javax.swing.JLabel();
        lbIconVerify = new javax.swing.JLabel();
        LabelBits = new javax.swing.JLabel();
        LbAddTextBits = new javax.swing.JLabel();
        fondooo = new javax.swing.JLabel();
        jbsalir = new javax.swing.JButton();
        jbcontinuar = new javax.swing.JButton();
        jbcalcular = new javax.swing.JButton();
        btnMayor = new javax.swing.JButton();
        btnMenor = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        n1.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        n1.setForeground(new java.awt.Color(0, 0, 0));
        n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 50));

        resultado1.setBackground(new java.awt.Color(255, 229, 124));
        resultado1.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        resultado1.setForeground(new java.awt.Color(0, 0, 0));
        resultado1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultado1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        resultado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado1ActionPerformed(evt);
            }
        });
        jPanel1.add(resultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 205, 40, 33));

        n2.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        n2.setForeground(new java.awt.Color(0, 0, 0));
        n2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 80, 50));
        jPanel1.add(lbIconVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 43, 40));

        LabelBits.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        LabelBits.setForeground(new java.awt.Color(0, 0, 0));
        LabelBits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LabelBits, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 40, 30));

        LbAddTextBits.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        LbAddTextBits.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(LbAddTextBits, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 23, 20, 20));

        fondooo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FrmExtraMYM.png"))); // NOI18N
        jPanel1.add(fondooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 420));

        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, 40, 40));

        jbcontinuar.setText("CONTINUAR");
        jbcontinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcontinuarActionPerformed(evt);
            }
        });
        jPanel1.add(jbcontinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 140, 33));

        jbcalcular.setText("CALCULAR");
        jbcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcalcularActionPerformed(evt);
            }
        });
        jPanel1.add(jbcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 130, 33));

        btnMayor.setText("jButton1");
        btnMayor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMayorMouseClicked(evt);
            }
        });
        btnMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorActionPerformed(evt);
            }
        });
        jPanel1.add(btnMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 40, 40));

        btnMenor.setText("jButton1");
        btnMenor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenorMouseClicked(evt);
            }
        });
        btnMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 270, 40, 40));

        btnIgual.setText("jButton1");
        btnIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualMouseClicked(evt);
            }
        });
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        jPanel1.add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 270, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado1ActionPerformed

    private void jbcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcalcularActionPerformed
        if (!okCalcular) {

            String c1, c2, c3;
            c1 = verificarigualdad(n11, n21);
            c2 = verificarigualdad(n31, n41);
            c3 = verificarigualdad(n51, n61);

            if (c1.equals(resultado)) {
                lbIconVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconTrueExtraMYM.png")));
                ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].OpCorrecta();
                actualizarBits();
                LbAddTextBits.setText("+5");
                LbAddTextBits.setForeground(new Color(103, 141, 88));
                okCalcular = true;
            } else {
                jbcontinuar.setEnabled(true);
                lbIconVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconFalseExtraMYM.png")));
                ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].OpIncorrecta();
                actualizarBits();
                LbAddTextBits.setText("-3");
                LbAddTextBits.setForeground(new Color(239, 99, 81));
            }
        }
    }//GEN-LAST:event_jbcalcularActionPerformed

    private String verificarigualdad(int a, int b) {
        String c = "";

        if (a > b) {
            c = ">";
        } else if (a < b) {
            c = "<";
        } else if (a == b) {
            c = "=";
        }

        return c;
    }

    public void actualizarBits() {

        LabelBits.setText(String.valueOf(ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getBits()));
    }

    private void jbcontinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcontinuarActionPerformed
        okCalcular = false;
        nuevaOp();
        actualizarBits();

        resultado1.setText("");
        LbAddTextBits.setText("");
        lbIconVerify.setIcon(null);

    }//GEN-LAST:event_jbcontinuarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        FrmExtras a = new FrmExtras();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbsalirActionPerformed

    private void btnMayorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMayorMouseClicked

    }//GEN-LAST:event_btnMayorMouseClicked

    private void btnMenorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenorMouseClicked

    }//GEN-LAST:event_btnMenorMouseClicked

    private void btnIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualMouseClicked

    }//GEN-LAST:event_btnIgualMouseClicked

    private void btnMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorActionPerformed
        resultado = ">";
        resultado1.setText(resultado);
    }//GEN-LAST:event_btnMayorActionPerformed

    private void btnMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorActionPerformed
        resultado = "<";
        resultado1.setText(resultado);
    }//GEN-LAST:event_btnMenorActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        resultado = "=";
        resultado1.setText(resultado);
    }//GEN-LAST:event_btnIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMayorMenorIgual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMayorMenorIgual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMayorMenorIgual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMayorMenorIgual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMayorMenorIgual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBits;
    private javax.swing.JLabel LbAddTextBits;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMayor;
    private javax.swing.JButton btnMenor;
    private javax.swing.JLabel fondooo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbcalcular;
    private javax.swing.JButton jbcontinuar;
    private javax.swing.JButton jbsalir;
    private javax.swing.JLabel lbIconVerify;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JTextField resultado1;
    // End of variables declaration//GEN-END:variables

}
