package Extras;

import Principal.FrmExtras;
import Principal.ListaUsuarios;
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Victor
 */
public class FrmOpCombinadas extends javax.swing.JFrame {

    int n1, B, n2, n3, rpta;
    String operacion;
    int maxSR = 50, minSR = 0;
    int maxMM = 10, minMM = 0, minMMB = 1;
    boolean okCalcular = false;

    /**
     * Creates new form ventana3
     */
    public FrmOpCombinadas() {
        initComponents();
        this.setLocationRelativeTo(null);
        nuevaOp();
        lblOperacion.setText(operacion);
        System.out.println(rpta);
        actualizarBits();
    }

    private void generarSuma() {
        n1 = (int) (Math.random() * (maxSR - minSR + 1) + minSR);
        B = (int) (Math.random() * (maxSR - minSR + 1) + minSR);
    }

    private void generarResta() {
        n1 = (int) (Math.random() * (maxSR - minSR + 1) + minSR);
        B = (int) (Math.random() * (n1 - minSR + 1) + minSR);
    }

    private void generarMultiplicacion() {
        n1 = (int) (Math.random() * (maxMM - minMM + 1) + minMM);
        B = (int) (Math.random() * (maxMM - minMM + 1) + minMM);
    }

    private void generarSumaB() {
        n2 = (int) (Math.random() * (B - minSR + 1) + minSR);
        n3 = B - n2;
    }

    private void generarRestaB() {
        n2 = (int) (Math.random() * (maxSR - B + 1) + B);
        n3 = n2 - B;
    }

    private void generarMultiplicacionB() {
        if (B == 0) {
            n2 = 0;
            n3 = (int) (Math.random() * (maxSR - minMM + 1) + minMM);
        } else {
            do {
                n2 = (int) (Math.random() * (B - minMMB + 1) + minMMB);
            } while (B % n2 != 0);
            n3 = B / n2;
        }
    }

    private void nuevaOp() {
        int caso = (int) (Math.random() * (9 - 1 + 1) + 1);
        switch (caso) {
            case 1: //n1 + (n2 + n3)
                generarSuma();
                generarSumaB();
                operacion = n1 + " + " + "(" + n2 + " + " + n3 + ")";
                rpta = n1 + (n2 + n3);
                break;
            case 2: //n1 + (n2 - n3)
                generarSuma();
                generarRestaB();
                operacion = n1 + " + " + "(" + n2 + " - " + n3 + ")";
                rpta = n1 + (n2 - n3);
                break;
            case 3: //n1 + (n2 * n3)
                generarSuma();
                generarMultiplicacionB();
                operacion = n1 + " + " + "(" + n2 + " * " + n3 + ")";
                rpta = n1 + (n2 * n3);
                break;
            case 4: //n1 - (n2 + n3)
                generarResta();
                generarSumaB();
                operacion = n1 + " - " + "(" + n2 + " + " + n3 + ")";
                rpta = n1 - (n2 + n3);
                break;
            case 5: //n1 - (n2 - n3)
                generarResta();
                generarRestaB();
                operacion = n1 + " - " + "(" + n2 + " - " + n3 + ")";
                rpta = n1 - (n2 - n3);
                break;
            case 6: //n1 - (n2 * n3)
                generarResta();
                generarMultiplicacionB();
                operacion = n1 + " - " + "(" + n2 + " * " + n3 + ")";
                rpta = n1 - (n2 * n3);
                break;
            case 7: //n1 * (n2 + n3)
                generarMultiplicacion();
                generarSumaB();
                operacion = n1 + " * " + "(" + n2 + " + " + n3 + ")";
                rpta = n1 * (n2 + n3);
                break;
            case 8: //n1 * (n2 - n3)
                generarMultiplicacion();
                generarRestaB();
                operacion = n1 + " * " + "(" + n2 + " - " + n3 + ")";
                rpta = n1 * (n2 - n3);
                break;
            case 9: //n1 * (n2 * n3)
                generarMultiplicacion();
                generarMultiplicacionB();
                operacion = n1 + " * " + "(" + n2 + " * " + n3 + ")";
                rpta = n1 * (n2 * n3);
                break;
            default:
                System.out.println("Error");
                break;
        }
    }

    public void actualizarBits() {
        LabelBits.setText(String.valueOf(ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getBits()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOperacion = new javax.swing.JLabel();
        lblIgual = new javax.swing.JLabel();
        txtRpta = new javax.swing.JTextField();
        lbIconVerify = new javax.swing.JLabel();
        LabelBits = new javax.swing.JLabel();
        LbAddTextBits = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOperacion.setFont(new java.awt.Font("Consolas", 1, 32)); // NOI18N
        lblOperacion.setForeground(new java.awt.Color(0, 0, 0));
        lblOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOperacion.setToolTipText("");
        jPanel1.add(lblOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 340, 80));

        lblIgual.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblIgual.setForeground(new java.awt.Color(0, 0, 0));
        lblIgual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIgual.setText("=");
        lblIgual.setToolTipText("");
        jPanel1.add(lblIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 30, 40));

        txtRpta.setBackground(new java.awt.Color(255, 255, 255));
        txtRpta.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        txtRpta.setForeground(new java.awt.Color(0, 0, 0));
        txtRpta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRpta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 170, 80));

        lbIconVerify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbIconVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 70, 70));

        LabelBits.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        LabelBits.setForeground(new java.awt.Color(0, 0, 0));
        LabelBits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LabelBits, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 60, 50));

        LbAddTextBits.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        LbAddTextBits.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(LbAddTextBits, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 20, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FrmOP.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 230, 50));

        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 230, 60));

        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        nuevaOp();
        lblOperacion.setText(operacion);
        System.out.println(rpta);
        LbAddTextBits.setText("");
        txtRpta.setText("");
        okCalcular = false;
        lbIconVerify.setIcon(null);
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FrmExtras a = new FrmExtras();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (!okCalcular) {
            if (rpta == Integer.parseInt(txtRpta.getText())) {
                lbIconVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconTrueExtraMYM.png")));
                ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].OpCorrecta();
                actualizarBits();
                LbAddTextBits.setText("+5");
                LbAddTextBits.setForeground(new Color(103, 141, 88));
                okCalcular = true;
            } else {
                btnContinuar.setEnabled(true);
                lbIconVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconFalseExtraMYM.png")));
                ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].OpIncorrecta();
                actualizarBits();
                LbAddTextBits.setText("-3");
                LbAddTextBits.setForeground(new Color(239, 99, 81));
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOpCombinadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOpCombinadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOpCombinadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOpCombinadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOpCombinadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LabelBits;
    private javax.swing.JLabel LbAddTextBits;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbIconVerify;
    private javax.swing.JLabel lblIgual;
    private javax.swing.JLabel lblOperacion;
    private javax.swing.JTextField txtRpta;
    // End of variables declaration//GEN-END:variables

}
