/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CuatroOp.Fracciones;

import Principal.FrmCuatroOp;
import Principal.ListaUsuarios;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Kevin-Martinez
 */
public class FrmFraccDiv extends javax.swing.JFrame {
    
    Boolean okCalcular = false;
    
    /**
     * Creates new form mainPrincipal
     */
    public FrmFraccDiv() {
        initComponents();
        setLocationRelativeTo(null);
        Random(fNum1);
        Random(fNum2);
        Random(fDeno1);
        Random(fDeno2);
        ActualizarBits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fNum1 = new javax.swing.JLabel();
        fDeno1 = new javax.swing.JLabel();
        fNum2 = new javax.swing.JLabel();
        fDeno2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        txtDeno = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        lbAddTextDiamonds = new javax.swing.JLabel();
        labelBits = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(132, 165, 157));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fNum1.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        fNum1.setForeground(new java.awt.Color(0, 0, 0));
        fNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fNum1.setText("15");
        fNum1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fNum1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(fNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 90, 80));

        fDeno1.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        fDeno1.setForeground(new java.awt.Color(0, 0, 0));
        fDeno1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fDeno1.setText("15");
        fDeno1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fDeno1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(fDeno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 90, 80));

        fNum2.setBackground(new java.awt.Color(0, 0, 0));
        fNum2.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        fNum2.setForeground(new java.awt.Color(0, 0, 0));
        fNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fNum2.setText("15");
        fNum2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fNum2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(fNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, 80));

        fDeno2.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        fDeno2.setForeground(new java.awt.Color(0, 0, 0));
        fDeno2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fDeno2.setText("15");
        fDeno2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fDeno2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(fDeno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 90, 80));

        label.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(0, 100, 0));
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 340, 30));

        txtDeno.setBackground(new java.awt.Color(204, 204, 204));
        txtDeno.setFont(new java.awt.Font("Consolas", 1, 55)); // NOI18N
        txtDeno.setForeground(new java.awt.Color(0, 0, 0));
        txtDeno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDeno.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDenoCaretUpdate(evt);
            }
        });
        jPanel1.add(txtDeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 110, 80));

        txtNum.setBackground(new java.awt.Color(204, 204, 204));
        txtNum.setFont(new java.awt.Font("Consolas", 1, 55)); // NOI18N
        txtNum.setForeground(new java.awt.Color(0, 0, 0));
        txtNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNum.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNumCaretUpdate(evt);
            }
        });
        jPanel1.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 110, 80));

        lbAddTextDiamonds.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lbAddTextDiamonds.setForeground(new java.awt.Color(0, 0, 0));
        lbAddTextDiamonds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbAddTextDiamonds, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 80, 30));

        labelBits.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        labelBits.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(labelBits, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 70, 60));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 100, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DivFracción.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        btnCalcular.setBackground(new java.awt.Color(255, 153, 153));
        btnCalcular.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorderPainted(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 130, 30));

        btnCerrar.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close-line.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        btnContinuar.setBackground(new java.awt.Color(255, 153, 153));
        btnContinuar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(0, 0, 0));
        btnContinuar.setText("Continuar");
        btnContinuar.setBorderPainted(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 130, 30));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        FrmCuatroOp Prin = new FrmCuatroOp();
        Prin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    public void Random(JLabel numero) {
        numero.setText("");
        int valor = (int) Math.round(Math.random() * 9 + 1);
        numero.setText(String.valueOf(valor));

        System.out.println(valor);
    }
    
    private void ActualizarBits() {
        labelBits.setText(String.valueOf(ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getBits()));
    }

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // ------- suma de fracciones---------
        int n1, n2, d1, d2, intNR, intDR, resultNum, resulDeno;

        if (txtNum.getText().length() != 0 && txtDeno.getText().length() != 0) {

            intNR = Integer.parseInt(txtNum.getText());
            intDR = Integer.parseInt(txtDeno.getText());
            n1 = Integer.parseInt(fNum1.getText());
            n2 = Integer.parseInt(fNum2.getText());
            d1 = Integer.parseInt(fDeno1.getText());
            d2 = Integer.parseInt(fDeno2.getText());

             double resultTemp = (n1*d2)/(d1*n2);
            double resultUser = intNR / intDR;

            if (!okCalcular) {
                if (resultTemp == resultUser) {
                    label.setForeground(new Color(103, 141, 88));
                    label.setText("¡Eso esta excelente, sigue así!");
                    ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].OpCorrecta();
                    ActualizarBits();
                    lbAddTextDiamonds.setText("+5");
                    okCalcular = true;
                } else {
                    label.setForeground(new Color(239, 99, 81));
                    label.setText("Eso no se ve bien, intentalo de nuevo");
                    ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].OpIncorrecta();
                    ActualizarBits();
                    lbAddTextDiamonds.setText("-3");
                }
            }

        } else {
            label.setForeground(Color.black);
            label.setText("Ingrese el resultado antes de calcular");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtDenoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDenoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDenoCaretUpdate

    private void txtNumCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNumCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCaretUpdate

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        okCalcular = false;
        
        Random(fNum1);
        Random(fNum2);
        Random(fDeno1);
        Random(fDeno2);

        txtNum.setText("");
        txtDeno.setText("");

        lbAddTextDiamonds.setText("");
        label.setText("");
        labelBits.setText("");
        ActualizarBits();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new WindInfoDiv().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFraccDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFraccDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFraccDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFraccDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFraccDiv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel fDeno1;
    private javax.swing.JLabel fDeno2;
    private javax.swing.JLabel fNum1;
    private javax.swing.JLabel fNum2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelBits;
    private javax.swing.JLabel lbAddTextDiamonds;
    private javax.swing.JTextField txtDeno;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
