package Geometria.Formularios;

import java.awt.Color;
import javax.swing.JOptionPane;
import Geometria.Clases.*;
import Geometria.Formularios.*;
import Principal.*;

public class FrmTriangulo extends javax.swing.JFrame {

    double base;
    double altura;
    double angulo;
    double area;
    
    Punto p0 = new Punto();
    Punto p1 = new Punto();
    Punto p2 = new Punto();
    Triangulo tri1 = new Triangulo();

    int i = 0;

    Boolean isNum;
    double scale = 1;

    Color bg;

    public FrmTriangulo() {
        initComponents();
        setLocationRelativeTo(null);
        initSlider();
        p0.definirCoord(0, PanelGrafico.getHeight() - 1);
        bg = PanelGrafico.getBackground();
    }

    private void initSlider() {
        sld_scale.setMinimum(1);
        sld_scale.setMaximum(7);
        sld_scale.setMajorTickSpacing(1);
        sld_scale.setPaintTicks(true);
        sld_scale.setValue(4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackground = new javax.swing.JPanel();
        txtBase = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtAngulo = new javax.swing.JTextField();
        PanelContenedor = new javax.swing.JPanel();
        PanelGrafico = new javax.swing.JPanel();
        sld_scale = new javax.swing.JSlider();
        lbl_slider = new javax.swing.JLabel();
        lbl_per = new javax.swing.JLabel();
        lbl_area = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnGraficar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBackground.setBackground(new java.awt.Color(255, 204, 51));
        PanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBase.setBackground(new java.awt.Color(241, 230, 184));
        txtBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseActionPerformed(evt);
            }
        });
        PanelBackground.add(txtBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 200, 80, 40));

        txtAltura.setBackground(new java.awt.Color(241, 230, 184));
        txtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });
        PanelBackground.add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 200, 80, 40));

        txtAngulo.setBackground(new java.awt.Color(241, 230, 184));
        txtAngulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnguloActionPerformed(evt);
            }
        });
        PanelBackground.add(txtAngulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 200, 80, 40));

        PanelContenedor.setBackground(new java.awt.Color(102, 102, 255));

        PanelGrafico.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout PanelGraficoLayout = new javax.swing.GroupLayout(PanelGrafico);
        PanelGrafico.setLayout(PanelGraficoLayout);
        PanelGraficoLayout.setHorizontalGroup(
            PanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        PanelGraficoLayout.setVerticalGroup(
            PanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelContenedorLayout = new javax.swing.GroupLayout(PanelContenedor);
        PanelContenedor.setLayout(PanelContenedorLayout);
        PanelContenedorLayout.setHorizontalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(PanelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        PanelContenedorLayout.setVerticalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(PanelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBackground.add(PanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 450, 300));

        sld_scale.setOrientation(javax.swing.JSlider.VERTICAL);
        sld_scale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sld_scaleStateChanged(evt);
            }
        });
        PanelBackground.add(sld_scale, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 30, 300));

        lbl_slider.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbl_slider.setForeground(new java.awt.Color(255, 102, 102));
        lbl_slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_slider.setText("jLabel1");
        PanelBackground.add(lbl_slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 80, 30));

        lbl_per.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_per.setForeground(new java.awt.Color(0, 0, 0));
        lbl_per.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelBackground.add(lbl_per, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 100, 40));

        lbl_area.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_area.setForeground(new java.awt.Color(0, 0, 0));
        lbl_area.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelBackground.add(lbl_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 100, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FrmTriangulo.png"))); // NOI18N
        PanelBackground.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        PanelBackground.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        btnGraficar.setText("GRAFICAR");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });
        PanelBackground.add(btnGraficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarExtrasTxf() {
        lbl_per.setText(tri1.per()+" cm");
        lbl_area.setText(area +" cm^2");
        System.out.println(tri1.area());
    }

    private void txtBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseActionPerformed
    }//GEN-LAST:event_txtBaseActionPerformed

    private void txtAnguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnguloActionPerformed
    }//GEN-LAST:event_txtAnguloActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed
    }//GEN-LAST:event_txtAlturaActionPerformed

    private void sld_scaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sld_scaleStateChanged
        switch (sld_scale.getValue()) {
            case 1:
                scale = 0.25;
                break;
            case 2:
                scale = 0.33;
                break;
            case 3:
                scale = 0.5;
                break;
            case 4:
                scale = 1;
                break;
            case 5:
                scale = 2;
                break;
            case 6:
                scale = 3;
                break;
            case 7:
                scale = 4;
                break;
            default:
                scale = 1;
        }
        lbl_slider.setText("" + scale);
        ValidarYGraficar();
    }//GEN-LAST:event_sld_scaleStateChanged

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        new FrmGeometria().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        base = Double.parseDouble(txtBase.getText());
        altura = Double.parseDouble(txtAltura.getText());
        angulo = Double.parseDouble(txtAngulo.getText());
        area = (base * altura)/2;
        ValidarYGraficar();
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void ValidarYGraficar() {
        
        Grafico.dibujarLinea(PanelGrafico.getGraphics(), p0, p1, bg);
        Grafico.dibujarLinea(PanelGrafico.getGraphics(), p1, p2, bg);
        Grafico.dibujarLinea(PanelGrafico.getGraphics(), p2, p0, bg);
        
        p0.definirCoord(0, PanelGrafico.getHeight() - 1);

        tri1.setAng1(angulo);
        tri1.setLado1(altura / Math.sin(Math.toRadians(angulo)));
        tri1.setLado3(base);
        //tri1.setLado2(Math.atan(altura / (tri1.getLado3() - altura/Math.tan(Math.toRadians(angulo)))));
        
        //Perímetro
        p1.x = (int) (altura / Math.tan(Math.toRadians(angulo)));
        p1.y = (int) (p0.y - (altura));
        
        p2.x = (int) (tri1.getLado3());
        p2.y = p0.y;
        
        tri1.setLado2(p1.dist(p2));
        //Perímetro
        
        p1.x = (int) (altura * scale / Math.tan(Math.toRadians(angulo)));
        p1.y = (int) (p0.y - (altura * scale));
        
        p2.x = (int) (tri1.getLado3() * scale);
        p2.y = p0.y;        
        
        Centrar();
        
        Grafico.dibujarLinea(PanelGrafico.getGraphics(), p0, p1, Color.black);
        Grafico.dibujarLinea(PanelGrafico.getGraphics(), p1, p2, Color.black);
        Grafico.dibujarLinea(PanelGrafico.getGraphics(), p0, p2, Color.black);
        
        actualizarExtrasTxf();
    }
    
    private void Centrar() {
        int desp = (PanelGrafico.getWidth() - p2.x)/2;
        p0.x += desp;
        p1.x += desp;
        p2.x += desp;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel PanelBackground;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelGrafico;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_per;
    private javax.swing.JLabel lbl_slider;
    private javax.swing.JSlider sld_scale;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAngulo;
    private javax.swing.JTextField txtBase;
    // End of variables declaration//GEN-END:variables
}
