package PensamientoLogico;

import PensamientoLogico.ParImpar.NodoBoton;
import PensamientoLogico.ParImpar.ListaBoton;
import PensamientoLogico.ParImpar.NodoInt;
import PensamientoLogico.ParImpar.ListaInt;
import Principal.FrmPensamientoLogico;
import Principal.Clases.ListaUsuarios;
import java.awt.Color;
import java.util.Random;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Victor
 */
public class FrmParImpar extends javax.swing.JFrame {

    ListaInt Lita;
    ListaBoton listaBotones = new ListaBoton();
    boolean espar;
    NodoInt nod;
    NodoBoton boton = listaBotones.inicio;
    boolean okCalcular = false;

    /**
     * Creates new form ventana3
     */
    public FrmParImpar() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarBits();
        this.lbl_par.setVisible(false);
        this.lbl_impar.setVisible(false);
        listaBotones.InsertarNodo(btn_1);
        listaBotones.InsertarNodo(btn_2);
        listaBotones.InsertarNodo(btn_3);
        listaBotones.InsertarNodo(btn_4);
        listaBotones.InsertarNodo(btn_5);
        listaBotones.InsertarNodo(btn_6);
        listaBotones.InsertarNodo(btn_7);
        listaBotones.InsertarNodo(btn_8);
        listaBotones.InsertarNodo(btn_9);
        crearnumeros();
        alternarniveles();
    }

    public void actualizarBits() {
        LabelBits.setText(String.valueOf(ListaUsuarios.matrizUsuarios[ListaUsuarios.posUsuario].getBits()));
    }

    public void crearnumeros() {
        Lita = new ListaInt();
        nod = Lita.inicio;
        JButton numeros[] = {btn_1, btn_2, btn_3, btn_4, btn_5, btn_6, btn_7, btn_8, btn_9};
        for (int i = 0; i < 9; i++) {
            numeros[i].setText(nod.dato + "");
            nod = nod.siguiente;
        }
    }

    public void alternarniveles() {
        Random random = new Random();
        int numeroAleatorio = random.nextInt(2);

        if (numeroAleatorio == 0) {
            this.lbl_par.setVisible(true);
            espar = true;

        } else {
            espar = false;
            this.lbl_impar.setVisible(true);
        }
    }

    public void backgroundblanco() {
        boton = listaBotones.inicio;
        for (int i = 0; i < 9; i++) {
            boton.dato.setBackground(Color.white);
            boton.dato.setForeground(Color.black);
            boton = boton.siguiente;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbIconVerify = new javax.swing.JLabel();
        LabelBits = new javax.swing.JLabel();
        LbAddTextBits = new javax.swing.JLabel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_par = new javax.swing.JLabel();
        lbl_impar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIconVerify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbIconVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 130, 130));

        LabelBits.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        LabelBits.setForeground(new java.awt.Color(0, 0, 0));
        LabelBits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LabelBits, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 60, 50));

        LbAddTextBits.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        LbAddTextBits.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(LbAddTextBits, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 20, 20));

        btn_1.setBackground(new java.awt.Color(255, 255, 255));
        btn_1.setForeground(new java.awt.Color(0, 0, 0));
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 110, 70));

        btn_2.setBackground(new java.awt.Color(255, 255, 255));
        btn_2.setForeground(new java.awt.Color(0, 0, 0));
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 110, 70));

        btn_3.setBackground(new java.awt.Color(255, 255, 255));
        btn_3.setForeground(new java.awt.Color(0, 0, 0));
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 110, 70));

        btn_4.setBackground(new java.awt.Color(255, 255, 255));
        btn_4.setForeground(new java.awt.Color(0, 0, 0));
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 110, 70));

        btn_5.setBackground(new java.awt.Color(255, 255, 255));
        btn_5.setForeground(new java.awt.Color(0, 0, 0));
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 110, 70));

        btn_6.setBackground(new java.awt.Color(255, 255, 255));
        btn_6.setForeground(new java.awt.Color(0, 0, 0));
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 110, 70));

        btn_7.setBackground(new java.awt.Color(255, 255, 255));
        btn_7.setForeground(new java.awt.Color(0, 0, 0));
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 110, 70));

        btn_8.setBackground(new java.awt.Color(255, 255, 255));
        btn_8.setForeground(new java.awt.Color(0, 0, 0));
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 110, 70));

        btn_9.setBackground(new java.awt.Color(255, 255, 255));
        btn_9.setForeground(new java.awt.Color(0, 0, 0));
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 110, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SELECCIONE LOS NÚMEROS QUE SON :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 260, 40));

        lbl_par.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_par.setForeground(new java.awt.Color(51, 51, 255));
        lbl_par.setText("PARES");
        jPanel1.add(lbl_par, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 70, 40));

        lbl_impar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_impar.setForeground(new java.awt.Color(0, 153, 0));
        lbl_impar.setText("IMPARES");
        jPanel1.add(lbl_impar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 90, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PensamientoLogico/Img/fondoParImpar.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 460));

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 210, 50));

        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 200, 50));

        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        LbAddTextBits.setText("");
        okCalcular = false;
        lbIconVerify.setIcon(null);

        this.lbl_par.setVisible(false);
        this.lbl_impar.setVisible(false);
        backgroundblanco();
        crearnumeros();
        alternarniveles();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        new FrmPensamientoLogico().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        boton = listaBotones.inicio;
        for (int i = 0; i < 9; i++) {
            if (espar == true) {
                if (boton.dato.getBackground().equals(Color.gray)) {
                    if (Integer.parseInt(boton.dato.getText()) % 2 == 0) {
                        boton.dato.setBackground(Color.green);
                        boton.dato.setForeground(Color.black);
                    } else {
                        boton.dato.setBackground(Color.red);
                        boton.dato.setForeground(Color.white);
                    }
                } else {
                    if (Integer.parseInt(boton.dato.getText()) % 2 != 0) {
                        boton.dato.setBackground(Color.green);
                        boton.dato.setForeground(Color.black);
                    } else {
                        boton.dato.setBackground(Color.red);
                        boton.dato.setForeground(Color.white);
                    }
                }
            } else {
                if (boton.dato.getBackground().equals(Color.gray)) {
                    if (Integer.parseInt(boton.dato.getText()) % 2 != 0) {
                        boton.dato.setBackground(Color.green);
                        boton.dato.setForeground(Color.black);
                    } else {
                        boton.dato.setBackground(Color.red);
                        boton.dato.setForeground(Color.white);
                    }
                } else {
                    if (Integer.parseInt(boton.dato.getText()) % 2 == 0) {
                        boton.dato.setBackground(Color.green);
                        boton.dato.setForeground(Color.black);
                    } else {
                        boton.dato.setBackground(Color.red);
                        boton.dato.setForeground(Color.white);
                    }
                }
            }
            boton = boton.siguiente;
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        if (btn_9.getBackground().equals(Color.white)) {
            btn_9.setBackground(Color.gray);
            btn_9.setForeground(Color.white);
        } else {
            btn_9.setBackground(Color.white);
            btn_9.setForeground(Color.black);
        }
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        if (btn_1.getBackground().equals(Color.white)) {
            btn_1.setBackground(Color.gray);
            btn_1.setForeground(Color.white);
        } else {
            btn_1.setBackground(Color.white);
            btn_1.setForeground(Color.black);
        }
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        if (btn_2.getBackground().equals(Color.white)) {
            btn_2.setBackground(Color.gray);
            btn_2.setForeground(Color.white);
        } else {
            btn_2.setBackground(Color.white);
            btn_2.setForeground(Color.black);
        }
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        if (btn_3.getBackground().equals(Color.white)) {
            btn_3.setBackground(Color.gray);
            btn_3.setForeground(Color.white);
        } else {
            btn_3.setBackground(Color.white);
            btn_3.setForeground(Color.black);
        }
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        if (btn_4.getBackground().equals(Color.white)) {
            btn_4.setBackground(Color.gray);
            btn_4.setForeground(Color.white);
        } else {
            btn_4.setBackground(Color.white);
            btn_4.setForeground(Color.black);
        }
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        if (btn_5.getBackground().equals(Color.white)) {
            btn_5.setBackground(Color.gray);
            btn_5.setForeground(Color.white);
        } else {
            btn_5.setBackground(Color.white);
            btn_5.setForeground(Color.black);
        }
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        if (btn_6.getBackground().equals(Color.white)) {
            btn_6.setBackground(Color.gray);
            btn_6.setForeground(Color.white);
        } else {
            btn_6.setBackground(Color.white);
            btn_6.setForeground(Color.black);
        }
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        if (btn_7.getBackground().equals(Color.white)) {
            btn_7.setBackground(Color.gray);
            btn_7.setForeground(Color.white);
        } else {
            btn_7.setBackground(Color.white);
            btn_7.setForeground(Color.black);
        }
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        if (btn_8.getBackground().equals(Color.white)) {
            btn_8.setBackground(Color.gray);
            btn_8.setForeground(Color.white);
        } else {
            btn_8.setBackground(Color.white);
            btn_8.setForeground(Color.black);
        }
    }//GEN-LAST:event_btn_8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmParImpar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmParImpar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmParImpar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmParImpar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmParImpar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LabelBits;
    private javax.swing.JLabel LbAddTextBits;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbIconVerify;
    private javax.swing.JLabel lbl_impar;
    private javax.swing.JLabel lbl_par;
    // End of variables declaration//GEN-END:variables

}
